### ISSUE TITLE
Let DataPackage viewer handle GitHub branches and directories

### ISSUE THREAD

**Issue by peterdesmet** [frictionlessdata/ideas#106]
I haven't thoroughly tested this, but it seems the [DataPackage Viewer](http://data.okfn.org/tools/view) only handles GitHub repositories where a) the repository = the datapackage, b) the datapackage lives on the `master` branch.

It would be nice if subdirectories were also supported, e.g. https://github.com/enram/data-challenge/tree/master/data/bird-migration-altitude-profiles

And alternative branches, to validate a data package before merging to master or to show an alternative version, e.g. https://github.com/peterdesmet/traffic-signs-hansbeke/tree/simple-data-format

**Comment by rgrp** [comment]
FIXED. Done in https://github.com/okfn/datapackage-identifier/pull/2

**Comment by peterdesmet** [comment]
Great! Is this already live at http://data.okfn.org/tools/view? I can't get the two examples listed above to work (yet).
