### ISSUE TITLE
Nice Owner/User page in data section

### ISSUE THREAD

**Issue by rgrp** [frictionlessdata/ideas#111]
Pages like: /data/{username}

Suggest

* [ ] Pull their gravatar and name (from github API)
  * Do we want to cache this?
* [ ] List their data packages (as per normal list)
  * Bonus for allowing quick filtering a la the main listing page

Note that "core" user will be special ... (will need to set their gravatar specialy)

### User Stories

As a Data User I want to see all the Data Packages produced by a particular organization or user so that I can find new ones that are relevant to me

* Especially, useful for core datasets
* List all datasets (no pagination for now!)

As a Data User I want to see all the Data Package produced by a particular organization or user so that I can get a sense of the quality of their work

**Comment by rgrp** [comment]
This would be really nice as we could then have http://data.okfn.org/data/core/

**Comment by rgrp** [comment]
@sxren are you interested in this one?

**Comment by sxren** [comment]
@rgrp yes.

**Comment by rgrp** [comment]
@sxren added some basic user stories

**Comment by rgrp** [comment]
@sxren let me know if you need anything. We can keep this super simple!

**Comment by sxren** [comment]
@rgrp thank you. i haven't made time to get into this yet.

**Comment by rgrp** [comment]
@sxren let me know if you have thoughts here. I'm just doing an upgrade to a nice new theme.

**Comment by sxren** [comment]
@rgrp  apologies for being so late getting back to you. started a new job and not so much free time at the moment. keen on being involved here again later.

if someone else wants to take this, please go ahead.

**Comment by rgrp** [comment]
@sxren no problem - and really appreciate your editorial assistance on the core datasets (hope you will still be able to contribute there!)

**Comment by rgrp** [comment]
@Deiz would you be interested in taking a look at this one?

**Comment by Deiz** [comment]
Yeah, I'll try implementing this in a few days. At a glance, the data package listing itself should be simple, but I'll probably need some feedback on the display of user information (web design isn't really in my wheelhouse).

**Comment by rgrp** [comment]
This issue was moved to okfn/data.okfn.org-new#13
