### ISSUE TITLE
Vision: edit this page button links to page itself

### ISSUE THREAD

**Issue by peterdesmet** [frictionlessdata/ideas#118]
I noticed a typo on http://data.okfn.org/vision, so I clicked the `Edit this page` button. It links however to the page itself, meaning nobody can contribute.

I assume the `Edit this page` button should link to the page on GitHub, where one can submit a pull request, similar to this page: http://data.okfn.org/tools?

**Comment by rgrp** [comment]
OBSOLETE / WONTFIX. No longer relevant with move to frictionlessdata.io.
