### ISSUE TITLE
Push (Tabular) Data Package to AWS Redshift

### ISSUE THREAD

**Issue by rgrp** [frictionlessdata/ideas#128]

**Comment by rgrp** [comment]
@roll is this now basically done thanks to http://github.com/frictionlessdata/datapackage-py and http://github.com/frictionlessdata/datapackage-sql-py? If so can we have a code snippet as a gist or inline here?

**Comment by roll** [comment]
I need to check it for Redshift.

**Comment by roll** [comment]
Code will be the same as for any Postgres database:

```python
# pip install sqlalchemy psycopg2 jsontableschema-sql git+git://github.com/frictionlessdata/datapackage-py
import sqlalchemy as sa
from datapackage import push_datapackage

# Redshift
REDSHIFT_URL = 'postgres://<user>:<pass>@<host>.redshift.amazonaws.com:5439/<database>'

# Engine
engine = sa.create_engine(REDSHIFT_URL)

# Import
push_datapackage(
    descriptor='https://raw.githubusercontent.com/datasets/country-codes/master/datapackage.json',
    backend='sql', engine=engine)

# Check
print(list(engine.execute('select * from data__country_codes')))
# will print data the same as in data/country_codes.csv
```

**Comment by tfmorris** [comment]
You don't need something like https://pypi.python.org/pypi/redshift-sqlalchemy to account for the SQL dialect differences?

**Comment by roll** [comment]
@tfmorris I'm not very familiar with Redshift system but from my testing driver makes simple queries not relying on some specific parts of dialect (so both `postrgres://` and  `redshift+psycopg2://` will be ok).

**Comment by rgrp** [comment]
FIXED. Working now. Need to document but that is separate in a tutorial - see #221
