### ISSUE TITLE
Updates to datapackage.json are not updated on the site

### ISSUE THREAD

**Issue by trickvi** [frictionlessdata/ideas#131]
If I update a data package descriptor file ``datapackage.json`` it does not get updated on the site (not until it gets reloaded/rebooted).

We need some sort of a mechanism to reload descriptor files. There are multiple ways of doing this but I think something like checking/storing ETag and providing a webhook or something else which would go and look if the ETag has changed. This way we could trigger updates to ``datapackage.json`` via webhooks.

Another option would be to introduce time limits to the internal cache so when we fetch from the internal cache it first checks to see if a certain amount of time has passed and would then refresh (probably via an ETag mechanism like in the other suggestion above).

**Comment by rgrp** [comment]
@tryggvib this is a great point. I guess we could just reboot every day atm but we do need a better solution.

**Comment by rgrp** [comment]
OK, I've introduced the `/admin/reload` api so that anyone can reload the database. We could find a way to call this regularly or just make sure to hit it after you've updated your datapackage.jon.

**Comment by rgrp** [comment]
FIXED.
