### ISSUE TITLE
datapackage.json / resources/dialect: Using Tabbed delimiter as "\t" not working

### ISSUE THREAD

**Issue by samperd** [frictionlessdata/ideas#132]
Hey Folks,

It was brought to my attention that my issue may be more with the datapackage.json reader, versus the spec. So I have moved the issue here.

Can someone help troubleshoot this issue. I have a file that contains a sha256 sum hash (I believe), followed by a tab, then followed by a file name (eg). There should be two rows.

The CSV dialect section of my datapackage.json does not seem to be behaving correctly:
1. Although I set header at false only one row shows, where there are two rows in the digest file
2. The collumn is not forming between the hash and file name

Tried:
1. "\t"
2. " "
3. " "

see in viewer here:
http://data.okfn.org/tools/view?url=https%3A%2F%2Fraw.githubusercontent.com%2Fsamperd%2Fec-datamart%2Fdevelop%2Fdata%2Fmanagementoversight%2Fsystems%2Fdata-mart-samples%2Fdatapackage.json#resource-digest

Related issue: https://github.com/dataprotocols/dataprotocols/issues/153

**Comment by rgrp** [comment]
OBSOLETE. We are working on this though in various places e.g. https://github.com/okfn/datapackage-render-js
