### ISSUE TITLE
datapackage.json line breaks in descriptors

### ISSUE THREAD

**Issue by samperd** [frictionlessdata/ideas#137]
Hey Folks,

I am wondering what is the proper way for allowing for line breaks in the datapackage.json file to show up in the package browser.

I have tried both \n and \r\n combinations to denote line breaks

The documentation mentions "description - a description of the package. The first paragraph (up to the first double line break should be usable as summary information for the package)"

So how do you do line breaks and double line breaks to be viewed in the viewer?

1. Example fails: http://data.okfn.org/tools/view?url=https%3A%2F%2Fraw.githubusercontent.com%2Fsamperd%2Fec-datamart%2Fdevelop%2Fdata%2Fmanagementoversight%2Fsystems%2Fdata-mart-samples%2Fghg-sources%2Fdatapackage.json#resource-sites

**Comment by rgrp** [comment]
FIXED.
