### ISSUE TITLE
Ideas for roadmap page

### ISSUE THREAD

**Issue by pwalsh** [frictionlessdata/ideas#168]
Some ideas for the current roadmap page (a brain dump): http://data.okfn.org/roadmap

* Relationship between tools/specs/community on this page, and the Tools and Standards pages proper
    * Maybe need a new object type in Jekyll that describes standard <> tooling <> community, and this can be used across site
* Tooling would be useful to group by language, and or indicate lang with icons. Tools that have CLIs should also be indicated clearly (due to potential for language agnostic use)
* Document a clear way to add tooling (user story: I just wrote a JTS validator in php - how do I add it to the list?)

**Comment by rgrp** [comment]
This issue was moved to frictionlessdata/frictionlessdata.io#11
