### ISSUE TITLE
DataPackage Viewer: check to see if README.md is returned correctly

### ISSUE THREAD

**Issue by morty** [frictionlessdata/ideas#189]
Currently the DataPackage View will include the README.md even if the page returns a 404 status code.

e.g.

http://data.okfn.org/tools/view?url=http%3A%2F%2Fmorty.co.uk%2Fdatapackage.json

**Comment by rgrp** [comment]
@morty great spot - another one to push down onto the underlying library https://github.com/okfn/datapackage-read - if you wouldn't mind. (It can also stay here until the fix is deployed).

**Comment by rgrp** [comment]
This issue was moved to okfn/datapackage-read-js#2
