### ISSUE TITLE
datapackage viewer will fail to render CSV preview when header name has '/' character

### ISSUE THREAD

**Issue by danfowler** [frictionlessdata/ideas#192]
https://raw.githubusercontent.com/os-data/boost-armenia/0ebc60aa6b24d3b63044035c58ca2ca59667a26e/datapackage.json

http://data.okfn.org/tools/view?url=https%3A%2F%2Fraw.githubusercontent.com%2Fos-data%2Fboost-armenia%2F0ebc60aa6b24d3b63044035c58ca2ca59667a26e%2Fdatapackage.json

Console yields:

    Error: Syntax error, unrecognized expression: Econ/func

**Comment by rgrp** [comment]
This issue was moved to okfn/datapackage-render-js#12
