### ISSUE TITLE
Datapackage viewer should provide all the validator info from Datapackage validator

### ISSUE THREAD

**Issue by danfowler** [frictionlessdata/ideas#193]
For example, when trying to view [this datapackage.json](https://raw.githubusercontent.com/os-data/boost-moldova/8fe97401080cb52b30acbb3ae491091166e90733/datapackage.json), I get the following error:

    There was an error.
    
    datapackage.json is invalid JSON. Details: Unexpected string

Much richer error info can be found in the validator (including the offending line number), but the viewer doesn't display it, nor does it link to the validator result.

**Comment by rgrp** [comment]
@danfowler great point. We'll get this fixed.

**Comment by rgrp** [comment]
This issue was moved to okfn/datapackage-validate-js#11
