### ISSUE TITLE
Deprecate core-list.txt to the benefit of core-list.csv

### ISSUE THREAD

**Issue by pdehaye** [frictionlessdata/ideas#208]
See datasets/registry/issues/159

**Comment by femtotrader** [comment]
my opinion is that data.okfn.org site should use a JavaScript DataPackage client

**Comment by pdehaye** [comment]
I have no opinion on what data.okfn.org should use. I do have opinions on what the registry should use. This would indeed be a datapackage itself, and it should rely on one csv and only one csv (no txt file) for each of the core and non-core lists. Ideally, adding a new datapackage to core would not require running anything, but simply adding a properly-formatted line would do.

**Comment by rgrp** [comment]
DUPLICATE - splitting out data.okfn.org specific issues from here. See:

https://github.com/okfn/data.okfn.org-new/issues/1
