### ISSUE TITLE
PHP JSON Table Validator Tool

### ISSUE THREAD

**Issue by georgewilde** [frictionlessdata/ideas#218]
Hey guys,

I've been working on an open source validator and storage library using the JSON table schema written in PHP.

This is a great utility library for validating that CSV files, streams or any other data source validates against a predefined JSON table schema definition.

It has some limitations and has been created due to a need for such a tool at the company I work for.

I thought I'd just let you know in case you thought it might be useful to others or thought it worth adding to your [Tools](http://data.okfn.org/tools) page.

Kind regards,

George Wilde

**Comment by danfowler** [comment]
@georgewilde That's fantastic and great to hear!  Please send me a link.  We're in the process of refactoring data.okfn.org and moving to http://frictionlessdata.io/.

Can you send me more info about your tool? I'll add it to http://frictionlessdata.io/tools/

**Comment by danfowler** [comment]
By the way, @georgewilde we have a [blog at Open Knowledge Labs](http://okfnlabs.org/blog/).  I'd love to have a post about the release of your tool.  I can help you put it together if you'd like, but the `README` is obviously a good starting point :smile:.

**Comment by georgewilde** [comment]
Hey @danfowler,

Thanks for getting back to me. I really like the new site and I can see that you've already added the tool there which is awesome. Do you still need any more detail from me or did you get enough from the README?

I'll definitely check out the tools for data packages on your Gitter chat and will happily write up a blog post for you. Is there any particular angle that would suit you or shall I just write something up about why we created it and why we're open sourcing it?

We're planning on posting something on our company blog too to mention it's release and that it's on the frictionless data website.

**Comment by rgrp** [comment]
@danfowler are you happy to respond here?

**Comment by rgrp** [comment]
Need to add under PHP section on tools page and then all good to go. @danfowler leading on this.

Thanks @georgewilde

**Comment by danfowler** [comment]
Thanks @georgewilde.  The library is now on the /tools/ page under the PHP section.  

https://github.com/frictionlessdata/frictionlessdata.io/commit/cb4610e2204437c6cb4d30ac6b55a6aeb69a9071

With respect to the blog post, the angle you suggest sounds perfect.  Cheers!

**Comment by rgrp** [comment]
@danfowler can we close this now?

**Comment by danfowler** [comment]
Closed by https://github.com/frictionlessdata/frictionlessdata.io/commit/cb4610e2204437c6cb4d30ac6b55a6aeb69a9071
