### ISSUE TITLE
Create example Data Packages

### ISSUE THREAD

**Issue by danfowler** [frictionlessdata/ideas#231]
As referenced in #221 

## Tabular
- [x] simple Tabular (one data file): 
https://github.com/frictionlessdata/example-data-packages/tree/master/periodic-table
- [x] Tabular (two data files): https://github.com/frictionlessdata/example-data-packages/tree/master/inflation
- [x] Tabular (two data files + foreign key): https://github.com/frictionlessdata/example-data-packages/tree/master/countries-and-currencies

## Geo
- [x] Geo data package: https://github.com/frictionlessdata/example-data-packages/tree/master/simple-geojson
- [x] Topo JSON: https://github.com/frictionlessdata/example-data-packages/tree/master/simple-topojson
- [x] Countries Geo data package: https://github.com/frictionlessdata/example-data-packages/tree/master/geo-countries

## Any
- [x] Any data: https://github.com/frictionlessdata/example-data-packages/tree/master/text-file

Purpose:

* Standard "test-suite" of datasets for developers to use
* Illustrative datasets for use in tutorials in demos

These are somewhat separate use cases and we may want to consider if we need two different sets e.g. maybe the developer test suite is quite special and should live in its own place.

**Comment by roll** [comment]
https://github.com/frictionlessdata/testsuite-py/tree/master/datasets

**Comment by rgrp** [comment]
AGREED:

* Separate "test-suite" data packages
* Tutorial data packages

This will avoid unintentional breakage or confusion.

In addition move all example / tutorial data packages to frictionlessdata org either in one repo or several.

**Comment by roll** [comment]
@danfowler 
gb-country-regional-analysis - one with PK and FKs you could use

**Comment by danfowler** [comment]
Examples for tutorials created.  Can delete these:

https://github.com/frictionlessdata/ex-geojson
https://github.com/frictionlessdata/ex-topojson

**Comment by rgrp** [comment]
@danfowler why would we delete those examples esp when we have redirects and perhaps outstanding links to them online?

**Comment by rgrp** [comment]
@danfowler could you add a README to https://github.com/frictionlessdata/example-data-packages explaining briefly that these are sample data packages used in tutorials (if that is correct). May be worth pointing to where stable data packages for testing may be found.

**Comment by danfowler** [comment]
@rgrp OK, let's keep the ex-* examples. I've updated their READMEs to point to the example-data-packages repo.  

I've updated the README for example-data-packages.
