### ISSUE TITLE
Tutorial: Validating Data

### ISSUE THREAD

**Issue by rgrp** [frictionlessdata/ideas#240]
General intro to validating data. Some of this may just be links out to other tutorials.

* [x] What is data "validation"?
* [x] Relevant specifications: JSON Table Schema
* [x] Tools
 * [x] GoodTables service
 * [x] Python + GoodTables
 * [x] Data Continuous Integration

Bonus:

* [ ] Type inference

**Comment by gsilvapt** [comment]
This issue will have its project being developed under https://github.com/okfn/handbook/issues/88 & https://github.com/okfn/handbook/issues/89

**Comment by rgrp** [comment]
@gsilvapt it will be relevant to those handbook issues but the work on the tutorial will go on here and on http://frictionlessdata.io/ 😄

**Comment by gsilvapt** [comment]
Oh, okay. I thought these would be the same and/or redirect to the same place. Doesn't that actually sounds more productive, @rgrp ? I know there are some differences, but some are actually the same - like these two I commented before.

**Comment by rgrp** [comment]
@gsilvapt if you are going to do work on this let's do it in this tracker. As per comments in handbook tracker we can reference FD.io stuff and extend it in some cases (e.g. core datasets).

Re:

> Also, isn't the Handbook supposed to contribute to the documentation of both (FLD + Coredatasets) projects?

FrictionlessData.io is the primary documentation location for Data Packages stuff. Core datasets item will likely to go Handbook as per e.g. https://github.com/okfn/handbook/issues/90

**Comment by danfowler** [comment]
FIXED: http://frictionlessdata.io/guides/validating-data/

**Comment by rgrp** [comment]
ACCEPTED.
