### ISSUE TITLE
Specifications repository and site

### ISSUE THREAD

**Issue by rgrp** [frictionlessdata/ideas#242]
`specs.frictionlessdata.io` - specifications site

Why a subsite? We want specs in a separate repo because we want separate issue tracking and for ease of transfer, versioning etc. Submoduling from that repo into main fd.io site would be painful => subsite. (That said there are big advantages all in one site e.g. theming ... hmmm).

* [x] move dataprotocols.org to this url
  * Need to split dataprotocols into "Data Package" specs which move and the rest which go to `specs.okfnlabs.org`
  * Qu: should this all go to specs.okfnlabs.org/. No: want data package in one coherent place

Steps:

* [x] Current dataprotocols repo => github.com/frictionlessdata/specs
* [x] Clone that repo and push to github.com/okfn/specs and set CNAME (we want at subdomain so we do not have path issues with baseurl)
* [x] Delete DP-related specs from specs.okfnlabs.org https://github.com/okfn/specs/pull/1
* [x] Announce changes
* [x] "Move" all open non-DP issues over to new repo
* [x] Link from fd.io main site
* [x] redirect dataprotocols.org -> specs.frictionlessdata.io OR specs.okfnlabs.org
* [ ] Fix front page of repo (change theme from dataprotocols etc)
* [ ] Apply FD theme to new repo

**Comment by danfowler** [comment]
@rgrp working on https://github.com/okfn/specs

**Comment by danfowler** [comment]
@rgrp specs here: http://specs.okfnlabs.org/

**Comment by danfowler** [comment]
@rgrp @pwalsh 

Q: redirect dataprotocols.org -> specs.okfnlabs.org or specs.frictionlessdata.io ? I guess we can assume more people are coming to dataprotocols.org looking for DP,TDP,JTS stuff.

**Comment by danfowler** [comment]
I think we can close this.  Theming, I think, can wait for more general design iteration.

**Comment by rgrp** [comment]
@danfowler i would have suggested implemented individual redirects at **DNS** level e.g. http://dataprotocols/linear-tsv/  should redirect to specs.okfnlabs.org/linear-tsv/ **not** http://specs.frictionlessdata.io/linear-tsv/ (and this would also mean you could actually get rid of this page in the specs.frictionlessdataio) site.

/cc @pwalsh (also going forward should I assume you are reviewing these items with @danfowler)

**Comment by pwalsh** [comment]
@rgrp yes I am.

**Comment by rgrp** [comment]
@pwalsh awesome 😄

**Comment by danfowler** [comment]
@rgrp @pwalsh that would be ideal.  I agree it is messy to have the /linear-tsv/ page on specs.frictionlessdata.io*.  Can you point to an example domain we're using that does a DNS redirect on a per-path basis like that?  I'm already using the special HTTP Redirect feature for dataprotocols.org -> specs.frictionlessdata.io.

*Once [this](https://github.com/jekyll/jekyll-redirect-from/releases/tag/v0.11.0) is updated on GitHub, the redirect should happen automatically

**Comment by rgrp** [comment]
@danfowler double-checking I think I am mistaken in DNSMadeEasy supporting path redirects as opposed to simple domain redirects 😦  If so, then what you have done is the only option (other than running our own nginx server for dataprotocols.org somewhere and implementing redirects - we use to do this but its not a great idea as it requires ongoing maintenance ...).

**Comment by pwalsh** [comment]
@rgrp correct, that is why I didn't get @danfowler to change his node-based redirects.

**Comment by rgrp** [comment]
@pwalsh annoying missing feature at DNS Made Easy (it looks like how they do this it would be pretty easy to implement ...).

**Comment by pwalsh** [comment]
@rgrp yes agreed.
