### ISSUE TITLE
Tutorial: Import Data into AWS Redshift

### ISSUE THREAD

**Issue by rgrp** [frictionlessdata/ideas#246]
Can probably just link to section in python tutorial but nice to have this on tutorials page.

**Comment by rgrp** [comment]
@danfowler can you leave a comment with "FIXED" in it here and a link to the actual result online - very useful for people who come here later (I would avoid closing "ideas" issues from commits in general).

**Comment by danfowler** [comment]
FIXED: http://frictionlessdata.io/guides/using-data-packages-in-python/

**Comment by rgrp** [comment]
@danfowler recommend linking to the specific section of the tutorial in this case e.g. http://frictionlessdata.io/guides/using-data-packages-in-python/#loading-into-amazon-redshift (aside: you probably want to add a table of contents to that tutorial now!)

**Comment by danfowler** [comment]
@rgrp good suggestion: added Reading Data section + ToC: http://frictionlessdata.io/guides/using-data-packages-in-python/#reading-data
