### ISSUE TITLE
Tutorial: Join two datasets together auto-magically

### ISSUE THREAD

**Issue by rgrp** [frictionlessdata/ideas#252]
As a Data Wrangler I want to download two datasets and join them together auto-magically so that I have one consolidated dataset

e.g. I have a dataset with country values (e.g. GDP) and i want to join on a dataset with geojson in it so i can do a map.

Or: i have data in nominal terms (e.g. GDP) and i want to join with Inflation and produce real GDP.

**Comment by danfowler** [comment]
@rgrp see https://github.com/danfowler/world_gdp_2014 for a Q&D example

**Comment by rgrp** [comment]
@danfowler nice - it would be good to get the world geojson from one of the existing data packages e.g. http://data.okfn.org/data/core/geo-countries

Guess a nice output would be a chloropeth map of the world as a view on the new data package.

So in summary, basic idea is:

* Take two source data packages
* Do a join to produce an output data package
  * Optionally add a view to this to show off the joined data
  * Or (simpler) just spit out a table with the data

If you want to know more about vega stuff ping me (and that's low priority vs the basic working setup).

**Comment by danfowler** [comment]
@rgrp FIXED: http://frictionlessdata.io/guides/joining-data-in-python/

**Comment by rgrp** [comment]
@danfowler have you opened a new issue for the second example? If so please reference in your closing of the issue.

**Comment by danfowler** [comment]
@rgrp new issue: https://github.com/frictionlessdata/ideas/issues/257

PR: https://github.com/frictionlessdata/frictionlessdata.io/pull/27
