### ISSUE TITLE
Support Hierarchical Data Profile for Data Packages

### ISSUE THREAD

**Issue by danfowler** [frictionlessdata/ideas#258]

**Comment by rgrp** [comment]
@danfowler do you mean tree-like data or ...?

**Comment by danfowler** [comment]
@rgrp this was just an example that came up during the hangout. I can close and re-add if and when I get better information.

**Comment by rgrp** [comment]
@danfowler when you close always state a reason if you can such as: "FIXED / INVALID / DUPLICATE / WONTFIX" e.g. here i think you wanted:

> INVALID.  This was just an example that came up during the hangout. I will close and re-add if and when I get better information.
