### ISSUE TITLE
Relational Database Support - Import

### ISSUE THREAD

**Issue by rgrp** [frictionlessdata/ideas#97]
* [x] #25 - sqlite
* [x] #26 - postgres
* [x] #165 + #164 - MS-SQL
* [x] Oracle
* [x] MySQL
* [ ] MariaDB

**Comment by rgrp** [comment]
I think this could be generified by having an SQL generator from Tabular Data Package schema plus backend specific copy commands (e.g. postgres has `COPY`).

**Comment by rgrp** [comment]
FIXED. See http://frictionlessdata.io/tools/#relational-databases and links therein e.g. https://github.com/frictionlessdata/datapackage-py#pushpull-data-package-to-storage

**Comment by ppKrauss** [comment]
Hi, about  `#26 - postgres`, https://github.com/okfn/dptools seems abandoned, there are other (plug-and-play) SQL tool?
